[files]
current_page=0
recent_files=/home/cobra/Workspace/Archives/new/config/wayfire/shell/standalones/shapes/right.qml;/home/cobra/Workspace/C/ROE/Chapter 11/05_realloc.c;/home/cobra/Workspace/C/ROE/Chapter 11/04_free.c;/home/cobra/Workspace/C/ROE/Chapter 11/03_quick_quiz.c;/home/cobra/Workspace/C/ROE/Chapter 11/02_quick_quiz.c;/home/cobra/Workspace/C/ROE/Chapter 11/01_dma.c;/home/cobra/Workspace/C/ROE/Chapter 1/07_escape_sequence.c;/home/cobra/Workspace/C/ROE/Chapter 1/06_input.c;/home/cobra/Workspace/C/ROE/Chapter 1/05_comments.c;/home/cobra/Workspace/C/ROE/Chapter 1/04_sizeof.c;
recent_projects=

[VTE]
last_dir=/home/liveuser

[project]
session_file=
project_file_path=

[geany]
treeview_position=156
msgwindow_position=472
geometry=20;45;654;699;0;
sidebar_page=0

[search]
find_all_expanded=false
replace_all_expanded=true
position_find_x=865
position_find_y=615
position_replace_x=855
position_replace_y=535
position_fif_x=675
position_fif_y=205

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=;
