#  ╔═╗╦╔═╗╔═╗╔╦╗  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗
#  ╠═╝║║  ║ ║║║║  ║  ║ ║║║║╠╣ ║║ ╦
#  ╩  ╩╚═╝╚═╝╩ ╩  ╚═╝╚═╝╝╚╝╚  ╩╚═╝
#
#  RUDV-AR - 2026
#  rules.conf — static window rules, appended by generate.sh
##################################################################

rules: (

    {
        blur-background = false;
        fade = false;
    },

    {
        match  = "window_type = 'normal'";
        fade   = true;
        shadow = true;
    },

    {
        match  = "window_type = 'dialog'";
        shadow = true;
    },

    {
        match         = "window_type = 'tooltip'";
        corner-radius = 0;
        opacity       = 0.90;
    },

    {
        match         = "fullscreen";
        corner-radius = 0;
    },

    {
        match         = "window_type = 'dock'";
        corner-radius = 0;
        fade          = true;
    },

    {
        match = "window_type = 'dropdown_menu' || "
                "window_type = 'menu'          || "
                "window_type = 'popup'         || "
                "window_type = 'popup_menu'";
        corner-radius = 0;
    },

    {
        match  = "window_type = 'menu' || role = 'popup' || role = 'bubble'";
        shadow = false;
    },

    {
        match = "class_g = 'alacritty'       || "
                "class_g = 'st-256color'     || "
                "class_g = 'kitty'           || "
                "class_g = 'alacritty-float' || "
                "class_g = 'toml-gui'        || "
                "class_g = 'ty-wall'         || "
                "class_g = 'vicinae'         || "
                "class_g = 'Alacritty'";
        opacity         = 0.93;
        corner-radius   = 5;
        blur-background = false;
    },
    {
        match = "class_g = 'Thunar'";
        opacity = 0.97;
        blur-background = false;
    },

    {
        match           = "class_g = 'scratch'";
        opacity         = 0.93;
        blur-background = false;
    },
    {
        match = "class_g = 'Alacritty'       || "
                "class_g = 'alacritty-float' || "
                "class_g = 'alacritty'";
        blur-background = false;
    },

    {
        match = "class_g = 'Polybar'   || "
                "class_g = 'Viewnior'  || "
                "class_g = 'Rofi'      || "
                "class_g = 'mpv'       || "
                "class_g = 'retroarch'";
        corner-radius = 0;
    },

    {
        match = "name = 'Notification'       || "
                "class_g ?= 'Notify-osd'     || "
                "class_g = 'Dunst'           || "
                "class_g = 'Polybar'         || "
                "class_g = 'jgmenu'          || "
                "class_g = 'firefox'         || "
                "class_g = 'mpv'             || "
                "_NET_WM_NAME = 'quickshell' || "
                "class_g = 'Viewnior'        || "
                "_GTK_FRAME_EXTENTS@";
        shadow = false;
    },

@include "animations.conf"

)
