#!/usr/bin/env bash


##################################################
# rudv-ar - 2026
##################################################

# bspwm directory
DIR="$HOME/.config/bspwm"

# rofi sudo askpass helper
export SUDO_ASKPASS="$DIR"/src/rofi_askpass

# execute the application
sudo -A $1
