#!/usr/bin/env bash


##################################################
# rudv-ar - 2026
##################################################
##
## launch kitty with bspwm config

# bspwm directory
DIR="$HOME/.config/bspwm/apps"
CONFIG="$DIR/kitty/kitty.conf"

if [ "$1" == "--float" ]; then
	kitty --class 'kitty-float' --config "$CONFIG"
elif [ "$1" == "--full" ]; then
	kitty --class 'kitty-fullscreen' --config "$CONFIG" \
		  --start-as fullscreen \
		  --override 'window_padding_width=30' \
		  --override 'font_size=14' \
		  --override 'background_opacity=0.95'
else
	kitty --config "$CONFIG" ${@}
fi
