#!/usr/bin/env bash


##################################################
# rudv-ar - 2026
##################################################
##
## Run ncmpcpp with alternate config

# bspwm directory
DIR="$HOME/.config/bspwm/apps"

CONFIG="$DIR/alacritty/alacritty.toml"

(alacritty --class 'Music,Music' -o window.dimensions.columns=105 window.dimensions.lines=10 "window.position={ x = 250, y = 500 }" -e cava &) && (alacritty --class 'Music,Music' --config-file "$CONFIG" \
		  -o window.dimensions.columns=105 window.dimensions.lines=22 "window.position={ x = 250, y = 50 }"\
		  -e ncmpcpp &)
