#!/usr/bin/env bash


##################################################
# rudv-ar - 2026
##################################################

# Import Current Theme
DIR="$HOME/.config/bspwm"
RASI="$DIR/rofi/windows.rasi"

# Run
rofi \
    -show window \
	-theme ${RASI}
